export const ACCEPT_LANDMARK = 'ACCEPT_LANDMARK';
export const RECEIVE_LANDMARKS = 'RECEIVE_LANDMARKS';
export const RECEIVE_METADATA = 'RECEIVE_METADATA';
export const RECEIVE_LATITUDE = 'RECEIVE_LATITUDE';
export const RECEIVE_LONGITUDE = 'RECEIVE_LONGITUDE';
export const RECEIVE_POINT = 'RECEIVE_POINT';
export const RECEIVE_ZOOM = 'RECEIVE_ZOOM';

export const ADD_IMAGES = 'ADD_IMAGES';
export const ADD_IMAGE_URL = 'ADD_IMAGE_URL';
export const DELETE_UPLOADER_IMAGE = 'DELETE_UPLOADER_IMAGE';

export const UPDATE_NEXT_LOCATION = 'UPDATE_NEXT_LOCATION';

export const SAVE_LOGGED_IN_USER = 'SAVE_LOGGED_IN_USER';
export const RESET_USER = 'RESET_USER';

export const TURN_MENU_ON = 'TURN_MENU_ON';
export const TURN_MENU_OFF = 'TURN_MENU_OFF';
export const TOGGLE_MENU = 'TOGGLE_MENU';
