export const UPDATE_LATITUDE = 'UPDATE_LATITUDE';
export const UPDATE_LONGITUDE = 'UPDATE_LONGITUDE';
export const UPDATE_ZOOM = 'UPDATE_ZOOM';

export const ADD_IMAGES = 'ADD_IMAGES';
export const ADD_IMAGE_URL = 'ADD_IMAGE_URL';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_URL = 'DELETE_IMAGE_URL';

export const UPDATE_NEXT_LOCATION = 'UPDATE_NEXT_LOCATION';

export const UPDATE_USER = 'UPDATE_USER';
