export const ACCEPT_LANDMARK = 'ACCEPT_LANDMARK';
export const RECEIVE_METADATA = 'RECEIVE_METADATA';
export const UPDATE_LATITUDE = 'UPDATE_LATITUDE';
export const UPDATE_LONGITUDE = 'UPDATE_LONGITUDE';
export const UPDATE_ZOOM = 'UPDATE_ZOOM';
